# These provide us a way of injecting environment variables into the pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: demo-prod
data:
  POSTGRES_DB: "kubetutorial101"
  POSTGRES_USER: "postgres"
  RUN_IN_PRODUCTION: "True"
  AWS_S3_REGION_NAME: "us-west-2"


